development:
  adapter: mysql
  database: gat_development
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql
  database: gat_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: gat_production
  username: root
  password: 
  host: localhost

cucumber:
  <<: *TEST
