#
# This file takes care of some key strings for the interface and app.
# You will also need to edit environment.rb with your own email settings.
# 

# This block defines defaults, shared for all environments.
# You can override them individually under development, test or production.
defaults: &DEFAULTS
  support: support@giveawathings.org

  # localhost:3000
  gmaps_key: ABQIAAAAGfRxw9a0TtglOmFFz2DztBTJQa0g3IQ9GZqIMmInSLzwtGDKaBTj0dfumRqbQiOKNLpWKDPpMo0wkw

  # The domain from where your app is served from. 
  app_domain: www.giveawaythings.org

  # Configuration for outgoing mail
  # By default, will send emails in production mode but not in development.
  outgoing:
    from: www.giveawaythings.org # the domain your emails will come from, as in no_reply@giveawaythings.org
    host: smtp.google.com        # the actual SMTP server used to deliver emails. can be a local or remote server
    user: no-reply@giveawaythings.org
    pass: smtp55!@
    auth: plain                  # choose: plain, login, cram_md5    
    port: 587  
  
  oauth_providers:
    # This example is configured for http://localhost:3000. Uncomment it to test it.
    # Register for your own domain at http://github.com/account/applications
    # github:
    #   name: Github
    #   site: https://github.com
    #   client_id: abfe8d0a74b0344b111b
    #   secret_key: aad82e098d2015254fc9b34550d6f93c37c17952
    #   authorize_path: /oauth/authorize
    #   access_token_path: /oauth/access_token
    #   user_path: /api/v2/json/user/show
    facebook:
      name: Facebook
      site: https://graph.facebook.com
      client_id: bc52bf6b4ea8fa42df28d66569e840d7
      secret_key: f2bd94d90abef946d0f4fa70a1ebfbdc
      authorize_path: /oauth/authorize
      access_token_path: /oauth/access_token
      user_path: /me
  

development:
  <<: *DEFAULTS
  app_domain: localhost:3000

production:
  <<: *DEFAULTS
  app_domain: www.giveawaythings.org

test: &TEST
  <<: *DEFAULTS
  app_domain: 127.0.0.1
  allow_outgoing_email: false
  asset_max_file_size: 1
cucumber:
  <<: *TEST  
